#ifndef __BOLLINGER_DEFS_MQH__
#define __BOLLINGER_DEFS_MQH__

// Enumerations for Bollinger Bands indicator

enum ENUM_BOLL_APPLIED_PRICE
  {
   BOLL_PRICE_CLOSE   = PRICE_CLOSE,
   BOLL_PRICE_OPEN    = PRICE_OPEN,
   BOLL_PRICE_HIGH    = PRICE_HIGH,
   BOLL_PRICE_LOW     = PRICE_LOW,
   BOLL_PRICE_MEDIAN  = PRICE_MEDIAN,
   BOLL_PRICE_TYPICAL = PRICE_TYPICAL,
   BOLL_PRICE_WEIGHTED= PRICE_WEIGHTED
  };

#endif // __BOLLINGER_DEFS_MQH__
